name: test-snap-tetymd
version-script: |
  git describe --tag | awk -F'-([1-9]|g)' '{print $1}'
version: latest
summary:  docui is TUI Client for Docker.
description: |
  docui is TUI Client for Docker.
grade: stable
confinement: classic

build-packages:
  - git
  - gcc

parts:
  testdocui:
    source: .
    plugin: go
    go-importpath: github.com/tetymd/testdocui
    build-snaps:
      - go/latest/stable
    override-build: |
      go build -o /build/test-snap-tetymd/parts/testdocui/go/bin/testdocui .

apps:
  test-snap-tetymd:
    command: testdocui
