name: test-snap-tetymd
version-script: |
  git describe --tag | awk -F'-([1-9]|g)' '{print $1}'
version: latest
summary:  docui is TUI Client for Docker.
description: |
  docui is TUI Client for Docker.
grade: stable
confinement: classic

parts:
  docui:
    source: .
    plugin: go
    go-importpath: github.com/tetymd/testdocui
    build-packages:
      - git
      - gcc
    build-snaps:
      - go/1.11/stable
    # override-build: |
      # go build -o $SANP/bin/docui .

apps:
  test-snap-tetymd:
    command: docui


