name: test-snap-tetymd
version-script: |
  git describe --tag | awk -F'-([1-9]|g)' '{print $1}'
version: latest
summary:  docui is TUI Client for Docker.
description: |
  docui is TUI Client for Docker.

grade: stable
confinement: classic

parts:
  docui:
    plugin: go
    go-importpath: github.com/skanehira/docui
    source: .
    build-packages:
      - gcc
    build-snaps:
      - go/latest/stable
    override-build: |
      mkdir bin
      go build -o bin/docui .

apps:
  test-snap-tetymd:
    command: bin/docui
